[build-system]
requires = ["setuptools>=45", "setuptools_scm[toml]>=6.2", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "hsnf"
description = "Computing Hermite normal form and Smith normal form."
readme = "README.md"
license = "MIT"
authors = [
    { name = "Kohei Shinohara" },
]
requires-python = ">=3.10"
dependencies = [
    "setuptools",
    "setuptools_scm",
    "wheel",
    "numpy>=1.20.1",
    "scipy",
]
classifiers = [
    "Development Status :: 2 - Pre-Alpha",
    "Intended Audience :: Science/Research",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: Implementation :: PyPy",
    "Topic :: Scientific/Engineering :: Mathematics",
]
dynamic = ["version"]

[project.optional-dependencies]
dev = [
    "pytest",
    "pytest-cov",
    "pre-commit",
    "ruff",
    "mypy",
]
docs = [
    "sphinx",
    "sphinx-autobuild",
    "sphinxcontrib-bibtex",
    "myst-parser",
    "sphinx-book-theme",
]

[project.urls]
Homepage = "https://github.com/lan496/hsnf"
Documentation = "https://hsnf.readthedocs.io/en/latest/"
Repository = "https://github.com/lan496/hsnf"

[tool.setuptools_scm]

[tool.setuptools.packages.find]
exclude = ["tests"]

[tool.setuptools.package-data]
hsnf = ["py.typed"]

[tool.pytest.ini_options]
testpaths = ["tests"]

[tool.coverage.run]
omit = ["tests/"]

[tool.ruff]
line-length = 99
exclude = ["docs"]

[tool.ruff.lint]
select = ["E", "F", "W", "C", "B", "UP", "I"]
ignore = ["E203", "E231", "E501"]

[tool.mypy]
exclude = [
  'docs',
]
