name: ci

on:
  push:
    branches: [master, develop]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Display Python version
      run: python -c "import sys; print(sys.version)"
    - name: Install
      run: |
        pip install --upgrade pip
        pip --version
        pip install -e .[dev]
    - name: Test with pytest
      run: |
        python -m pytest -v
